### ISSUE TITLE
Invariant Violation: You may be attempting to nest <Helmet> components within each other, which is not allowed. Refer to our API for more information.

### ISSUE THREAD

**Issue by igorshmukler** [staylor/react-helmet-async#154]
Hello,

I am trying to use `react-helmet-async@1.2.2` in order to `renderToNodeStream` an app made with `react@17.0.2`, redux and saga. It is NOT working for me. Without `Helmet`, everything is working fine, though I am missing important resources, title, etc - whatever I need `react-helmet-async` to generate. When `<Helmet>` is enabled, it just crashes.

My code is below:
```
      const helmetData = new HelmetData({});

      store
        .runSaga(rootSaga)
        .toPromise()
        .then(() => {
          frontloadServerRender(() =>
            // to support AMP, use renderToStaticMarkup()
            // we no longer care for AMP
            {
              const routeMarkupNodeStream = renderToNodeStream(
                <Capture report={m => modules.push(m)}>
                  <Helmet helmetData={helmetData}>
                    <Provider store={store}>
                      <StaticRouter location={req.url} context={context}>
                        <Frontload isServer={true}>
                          <App />
                        </Frontload>
                      </StaticRouter>
                    </Provider>
                  </Helmet>
                </Capture>
              );

              if (context.url) {
                // If context has a url property, then we need to handle a redirection in Redux Router
                res.writeHead(302, {
                  Location: context.url
                });
                res.end();
                return;
              }

              // Otherwise, we carry on...
              res.status(200);
              const state = store.getState();

              const { helmet } = helmetData.context;

              res.setHeader('Cache-Control', 's-maxage=0, private');

              if (context.status === 404) {
                res.status(404);
              }

              // Format assets into pretty <script> tags
              const extraChunks = extractAssets(manifest, modules).map(
                c =>
                  `<script type="text/javascript" src="/${c.replace(
                    /^\//,
                    ''
                  )}"></script>`
              );

              res.write(
                injectHeaderHTML(htmlData, {
                  html: helmet.htmlAttributes.toString(),
                  title: helmet.title.toString(),
                  meta: helmet.meta.toString(),
                  headScript: helmet.script.toString(),
                  link: helmet.link.toString()
                })
              );

              console.log('wrote head');

              // On fastify, we got to set the content to html
              // res.header('Content-Type', 'text/html');

              routeMarkupNodeStream.pipe(res, { end: false });

              routeMarkupNodeStream.on('pipe', () => {
                console.log('Piped!');
              });

              routeMarkupNodeStream.on('error', (e) => {
                console.log('Error:', e);
                res.status(500).send(e.message);
              });

              routeMarkupNodeStream.on('end', () => {
                res.end(
                  injectFooterHTML(cachedHtmlData, {
                    scripts: extraChunks,
                    state: JSON.stringify(state).replace(/</g, '\\u003c')
                  })
                );
                console.log('finished writing');
              });
            }
          );
        })
        .catch(e => {
          console.error('caught error');
          throw e;
        });
      // Let's do dispatches to fetch category and event info, as necessary
      const { dispatch } = store;
```
When I am running the above, it prints:

```
wrote head
caught error
Error: Invariant Violation: You may be attempting to nest <Helmet> components within each other, which is not allowed. Refer to our API for more information.
```

I am trying to convert my working SSR code from renderToString to renderToNodeStream, which became available in thew React.JS, for improved time-to-first-byte. I know that react-helmet is synchronous, and won't work with renderToNodeStream(), yet there are some "async" forks that people use to make helmet interoperate with async/stream rendering. I picked the react-helmet-async library for my experiments, and converted my code to the below:

  const helmetData = new HelmetData({});
  store
    .runSaga(rootSaga)
    .toPromise()
    .then(() => {
      frontloadServerRender(() =>
        // to support AMP, use renderToStaticMarkup()
        // we no longer care for AMP
        {
          const routeMarkupNodeStream = renderToNodeStream(
            <Capture report={m => modules.push(m)}>
              <Helmet helmetData={helmetData}>
                <Provider store={store}>
                  <StaticRouter location={req.url} context={context}>
                    <Frontload isServer={true}>
                      <App />
                    </Frontload>
                  </StaticRouter>
                </Provider>
              </Helmet>
            </Capture>
          );
          if (context.url) {
            // If context has a url property, then we need to handle a redirection in Redux Router
            res.writeHead(302, {
              Location: context.url
            });
            res.end();
            return;
          }

          // Otherwise, we carry on...
          const state = store.getState();

          const { helmet } = helmetData.context;

          // Let's format those assets into pretty <script> tags
          const extraChunks = extractAssets(manifest, modules).map(
            c =>
              `<script type="text/javascript" src="/${c.replace(
                /^\//,
                ''
              )}"></script>`
          );

          console.log('starting to write node-stream');
          console.log('html:', helmet.htmlAttributes.toString());
          console.log('title:', helmet.title.toString());

          res.write(
            injectHeaderHTML(cachedHtmlData, {
              html: helmet.htmlAttributes.toString(),
              title: helmet.title.toString(),
              meta: helmet.meta.toString(),
              headScript: helmet.script.toString(),
              link: helmet.link.toString()
            })
          );

          console.log('wrote head');

          // On fastify, we got to set the content to html
          // res.header('Content-Type', 'text/html');

          routeMarkupNodeStream.pipe(res, { end: false });

          routeMarkupNodeStream.on('pipe', () => {
            console.log('Piped!');
          });

          routeMarkupNodeStream.on('end', () => {
            res.end(
              injectFooterHTML(cachedHtmlData, {
                scripts: extraChunks,
                state: JSON.stringify(state).replace(/</g, '\\u003c')
              })
            );
            console.log('finished writing');
          });
        }
      );
    })
    .catch(e => {
      res.status(500).send(e.message);
    });
  // Let's do dispatches to fetch category and event info, as necessary
  const { dispatch } = store;
When I run the above code, it crashes with:

starting to write node-stream
html: 
title: <title data-rh="true"></title>
wrote head
events.js:292
      throw er; // Unhandled 'error' event
      ^

Invariant Violation: You may be attempting to nest <Helmet> components within each other, which is not allowed. Refer to our API for more information.
    at Object.invariant [as default] (/.../node_modules/invariant/invariant.js:40:15)
    at e.warnOnInvalidChildren (/.../node_modules/react-helmet-async/src/index.js:147:5)
    at /.../node_modules/react-helmet-async/src/index.js:188:14
    at /.../node_modules/react/cjs/react.development.js:1104:17
    at /.../node_modules/react/cjs/react.development.js:1067:17
    at mapIntoArray (/.../node_modules/react/cjs/react.development.js:964:23)
    at mapChildren (/.../node_modules/react/cjs/react.development.js:1066:3)
    at Object.forEach (/.../node_modules/react/cjs/react.development.js:1103:3)
    at e.mapChildrenToProps (/.../node_modules/react-helmet-async/src/index.js:172:20)
    at e.r.render (/.../node_modules/react-helmet-async/src/index.js:229:23)
Emitted 'error' event on ReactMarkupReadableStream instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  framesToPop: 1
}
I also tried `let helmetContext = {};` and wrapping my app with `<HelmetProvider context={helmetContext}>`. There, my helmetContext stays set to `{}`, so `const { helmet } = helmetContext;` returns `undefined`.

Suggestions?

**Comment by Blakeinstein** [comment]
I think the problem maybe you are trying to render elements not meant to be rendered on the head?
```html
<Helmet helmetData={helmetData}>
                    <Provider store={store}>
                      <StaticRouter location={req.url} context={context}>
                        <Frontload isServer={true}>
                          <App />
                        </Frontload>
                      </StaticRouter>
                    </Provider>
                  </Helmet>
                  ```
you are telling helmet to render store providers, routes and everything on the head,

Helment will only accept title, link, script and native HTML elements.

**Comment by igorshmukler** [comment]
@Blakeinstein I believe that you did not understand my code. Store providers and/or routes are meant to be rendered, nor there is a way to render them, as far as I know. The store needs to be initialized, though; and the app needs to be wrapped with all providers and to include the router if it uses one. There are plenty of simple SSR examples out there to review.

It seems to me that `react-helmet-async` requires multiple render passes, in my case. Specifically, for it to work, before `const { helmet } = helmetData.context;`, we need to do something like `renderToString(app)` or `renderToStaticMarkup(app)`, else there is nothing in the context. Meaning that to use an async `renderToNodeStream`, we need to do a synchronous rendering first.

If the above is correct, I don't see how using `react-helmet-async` with `renderToNodeStream()` could be better than `react-helmet` with `renderToString()`. Seems like an effort without an ROI. Perhaps, someone with different requirements managed to find it beneficial, like perhaps extracting GraphQL data allows doing one pass. I don't personally see the point. Perhaps, I am wrong about multiple passes.

**Comment by Blakeinstein** [comment]
> @Blakeinstein I believe that you did not understand my code. Store providers and/or routes are not meant to be rendered, nor there is a way to render them, as far as I know. The store needs to be initialized, though; and the app needs to be wrapped with all providers and to include the router if it uses one. There are plenty of simple SSR examples out there to review.

Interesting I was thinking more in the lines of your rough markup looking something like this.

```html
                <Capture report={m => modules.push(m)}>
                  <HelmetProvider>
                    <Provider store={store}>
                      <StaticRouter location={req.url} context={context}>
                        <Frontload isServer={true}>
						  <Helmet>
							<title>Some title</title>
						  </Helmet>
                          <App />
                        </Frontload>
                      </StaticRouter>
                    </Provider>
                  </HelmetProvider>
                </Capture>
```

what I meant to point out was the childer for the <Helmet> component should only be valid head tags, it is something I figured just now as helmet didn't seem to like my custom components which internally wrote script tags.

```html
<Helmet><Head /></Helmet>
```
doesn't work but
```html
<Helmet>{head()}</Helmet>
```
does,
where my head component conditionally returns 
<script>gtag script</script> based on env

**Comment by nickdaugherty** [comment]
There are valid use cases for rendering non-html children of `<Helmet />`, such as when you want to encapsulate the logic of generate tags into a reusable component, for example, a set of OpenGraph tags.
