### ISSUE TITLE
Compatibiliy with Jest

### ISSUE THREAD

**Issue by ivan-kleshnin** [staylor/react-helmet-async#34]
Hi! Does anyone has success with this library and Jest? I replaced Helmet with Helmet-Async to avoid that bug with infinite recursion... Now I got some incompatibility with Jest (which I didn't have back then with original Helmet). 

```
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [TypeError: Cannot read property 'add' of undefined]
          at reportException (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at invokeEventListeners (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
          at HTMLUnknownElementImpl._dispatch (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at Object.invokeGuardedCallbackDev (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:199:16)
          at invokeGuardedCallback (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:256:31)
          at replayUnitOfWork (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:17228:5)
          at renderRoot (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:18100:13) TypeError: Cannot read property 'add' of undefined
          at Dispatcher.init (/Users/username/Projects/projectname/node_modules/react-helmet-async/lib/Dispatcher.js:72:23)
          at Dispatcher.render (/Users/username/Projects/projectname/node_modules/react-helmet-async/lib/Dispatcher.js:116:12)
          at finishClassComponent (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:14418:31)
          at updateClassComponent (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:14381:10)
          at beginWork (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:15203:16)
          at performUnitOfWork (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:17941:12)
          at workLoop (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:17981:24)
          at callCallback (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:149:14)
          at batch (/Users/username/Projects/projectname/node_modules/react-easy-state/dist/cjs.es6.js:36:15)
          at HTMLUnknownElement.batched (/Users/username/Projects/projectname/node_modules/react-easy-state/dist/cjs.es6.js:55:28)
          at invokeEventListeners (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
          at HTMLUnknownElementImpl._dispatch (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (/Users/username/Projects/projectname/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at Object.invokeGuardedCallbackDev (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:199:16)
          at invokeGuardedCallback (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:256:31)
          at replayUnitOfWork (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:17228:5)
          at renderRoot (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:18100:13)
          at performWorkOnRoot (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:18958:7)
          at performWork (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:18870:7)
          at performSyncWork (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:18844:3)
          at requestWork (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:18713:5)
          at scheduleWork (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:18522:5)
          at dispatchAction (/Users/username/Projects/projectname/node_modules/react-dom/cjs/react-dom.development.js:12122:5)
          at updater (/Users/username/Projects/projectname/node_modules/react-easy-state/dist/cjs.es6.js:141:31)
          at runTask (/Users/username/Projects/projectname/node_modules/react-easy-state/dist/cjs.es6.js:28:3)
          at Set.forEach (<anonymous>)
          at batch (/Users/username/Projects/projectname/node_modules/react-easy-state/dist/cjs.es6.js:40:13)
          at batched (/Users/username/Projects/projectname/node_modules/react-easy-state/dist/cjs.es6.js:55:28)
          at process._tickCallback (internal/process/next_tick.js:68:7)
```

I now it's an ugly chunk of code but if you inspect it, you see that it's caused by react-helmet-async.
It happens only in Jest, no problems in browser. Use-case has nothing special:

```jsx
function Layout(props) {
  ...
  return [
      document && <Helmet key="0">
        <meta charSet="utf-8" />
        <title>{document.seoTitle}</title>
        <meta name="description" content={document.seoDescription}/>
        <meta property="og:type" content={document.ogType}/>
        <meta property="og:image" content={document.ogImage}/>
      </Helmet>,
  ...
```

if I remove `<Helmet>...</Helmet>`, the above problem disappears. I didn't forget to add provider like this:

```
export default function App (props) {
  return <HelmetProvider context={helmetContext}>
    <Router>
```

**Comment by ivan-kleshnin** [comment]
Thanks. I switched to NextJS recently so I don't have time to check back this issue. Closing...

**Comment by venku122** [comment]
You can globally mock `react-helmet-async` to resolve this issue.

```
/**
 * Mock helmet module
 */
jest.mock('react-helmet-async', () => ({
  Helmet: () => jest.fn(),
  HelmetProvider: () => jest.fn(),
}));
```

**Comment by thomasjulianstoelen** [comment]
Update for 2023:

Using the above solution you'll encounter the following error:

`
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
`

To overcome this we just need to wrap the component with the correct providers. I've included <BrowserRouter /> to show that a project might have more than one provider (Redux, Helmet, BrowserRouter and others etc).

```
/**
 * @jest-environment jsdom
 */
import { test, expect, jest } from "@jest/globals";
import React from "react";
import { render } from "@testing-library/react";
import { BrowserRouter } from "react-router-dom";
import { HelmetProvider } from "react-helmet-async";

import MyComponent from "src/components/MyComponent.jsx";

const Providers = ({ children }) => {
  HelmetProvider.canUseDOM = false;

  return (
    <HelmetProvider>
      <BrowserRouter>
        {children}
      </BrowserRouter>
    </HelmetProvider>
  );
};

test("renders MyComponent", () => {
  render(<MyComponent />, { wrapper: Providers });
});
```

**Comment by laneschmidt** [comment]
@thomasjulianstoelen thanks for getting me unstuck on this one 🤝

however i encountered another issue. it seems that using this pattern results in an empty dom being rendered:

```
<body>
  <div />
</body>
```

could be something unrelated but the code works without `HelmetProvider`, it just yields that annoying warning.

here is the code:

```
HelmetProvider.canUseDOM = false;
const renderIt = (results: Result) => {
  render(
    <HelmetProvider>
      <BrowserRouter>
        <ResultsStateContext.Provider
          value={{
            results: { Province: 'SomeProvince', ...results },
            setResults: () => ({}),
          }}
        >
          <HiriComponent />
        </ResultsStateContext.Provider>
      </BrowserRouter>
    </HelmetProvider>,
  );
};
```
